### ISSUE TITLE
/mirror command not working in new "Topics" chat.

### ISSUE THREAD

**Issue by LeviSnoot** [Syfaro/foxbot#118]
Since switching my group to topic based chat, the `/mirror` command doesn't seem to work with FoxBot. See screenshot attached below.
It has no problem reverse searching images though.

![image](https://user-images.githubusercontent.com/13402525/201701555-7f095950-eb5f-4bb4-8db5-ca28568e1268.png)

**Comment by Syfaro** [comment]
I haven't used topics yet, but is there something preventing you from directly replying to the message? The `/mirror` command only works if the link is in the same message as the command or in direct reply to a message with the link (which that doesn't appear to be).
